### ISSUE TITLE
webflow demo does not work

### ISSUE THREAD

**Issue by kun432** [voiceflow/runtime-client-js#51]
I want to check webflow demo for implmenting web chat, but it does not respond anything.

![s_111](https://user-images.githubusercontent.com/3592894/111054846-406f9900-84b3-11eb-9410-a8c179b664dd.png)

![s_112](https://user-images.githubusercontent.com/3592894/111054862-567d5980-84b3-11eb-8512-01347680317d.png)

![s 113](https://user-images.githubusercontent.com/3592894/111054879-62691b80-84b3-11eb-9f47-379a6fd4d9e3.png)

also, I'd like to see source code if possible. Thanks.

**Comment by DecathectZero** [comment]
@kun432 sorry this demo is totally out of date - it doesn't account for API keys which is the problem.

I wrote the source code down below, but it definitely needs an update.
https://github.com/DecathectZero/chat-widget
https://github.com/DecathectZero/chat-window
