### ISSUE TITLE
Custom Action - select path (VF-876)

### ISSUE THREAD

**Issue by fosteman** [voiceflow/runtime-client-js#58]
Hi there,
I have here a Custom Action with 2 paths, and the trace object on the frontend.
<img width="218" alt="Screen Shot 2021-05-03 at 9 54 41 PM" src="https://user-images.githubusercontent.com/32850517/116953023-2e5fda80-ac5a-11eb-840f-8313fa369c98.png">
<img width="464" alt="Screen Shot 2021-05-03 at 9 55 23 PM" src="https://user-images.githubusercontent.com/32850517/116953067-4df70300-ac5a-11eb-9226-570e24a1494e.png">

It seems as though the `stopTypes` or even `stopAll` wouldn't actually stop on the action, and instead lead me to the end of the conversation by selecting the default path automatically.
<img width="347" alt="Screen Shot 2021-05-07 at 9 17 50 AM" src="https://user-images.githubusercontent.com/32850517/117455350-1962a000-af15-11eb-8b58-93fc914d50fe.png">

You guys are doing amazing job, I just turned away from DialogflowCX for this and can't stop but to applaud your ingenuity. Let's make this product better!

**Comment by fosteman** [comment]
Okay, here's an update!
With new update `v1.353.0`, stopping on types works, though I still can't continue down a path. 

Here's how it looks like in action:
<img width="685" alt="Screen Shot 2021-05-09 at 3 52 41 PM" src="https://user-images.githubusercontent.com/32850517/117585101-98570480-b0de-11eb-8971-9d6db4b625b7.png">

1. I am receiving the Custom Action block and the trace has the continuation in it (why is that?) 
2. Once I 
```API.voiceFlowClient
            .sendRequest({
              type: "default",
              payload: null,
            })
```, the trace abruptly ends.

**Comment by fosteman** [comment]
Forum thread with more screenshots and details: https://forum.voiceflow.com/t/custom-actions-how-do-they-work/2052

**Comment by jonahsnider** [comment]
Hey Timothy, sorry to hear you're having issues with the SDK. Our team is currently investigating this issue. If we have any questions or find a solution we'll reply here.

**Comment by jonahsnider** [comment]
After investigating we found a bug in the logic for default branches which may have been responsible for the issue you encountered. Update to [v1.17.1](https://github.com/voiceflow/runtime-client-js/releases/tag/v1.17.1) and try changing `.onSpeak` to `.onResponse`. An example of this can be seen [here](https://github.com/voiceflow/rcjs-examples/tree/master/hamburger-order-react).
