### ISSUE TITLE
Does not stop on a custom action type

### ISSUE THREAD

**Issue by fosteman** [voiceflow/runtime-client-js#60]
I have here a custom action defined.
<img width="592" alt="Screen Shot 2021-05-13 at 8 30 28 PM" src="https://user-images.githubusercontent.com/32850517/118203427-0f1b3700-b42a-11eb-9776-a7a10160804a.png">

Here's how my client is configured 
```
const factory = new RuntimeClientFactory({
  versionID: "...",
  apiKey:
    "VF...",
  dataConfig: {  
   stopAll: true,
    stopTypes: ["test"],
  },
});
```
But the client will not stop on the custom action, it'll instead jump right ahead to the "speak" block

**Comment by jonahsnider** [comment]
Can you share more about the project you're having issues with? Specifically, sharing the source for your `onResponse` listener you're setting can help us reproduce the issue on our end. Also, make sure you're using the latest version of the package.

**Comment by fosteman** [comment]
```
this.voiceFlowClient.on(TraceEvent.GENERAL, addTraceToBoard);
const addTraceToBoard = (
trace: GeneralTrace,
  context?: Context,
  index?: number) => {
 switch (String(trace.type)) {
...
}
}

**Comment by fosteman** [comment]
@jonahsnider thanks for replying!
Here's the information to reproduce. Though the source is rather simplistic (it's from documentation and works wonders)

```
this.voiceFlowClient.on(TraceEvent.GENERAL, addTraceToBoard);
const addTraceToBoard = (
trace: GeneralTrace,
  context?: Context,
  index?: number) => {
 switch (String(trace.type)) {
...
}
}
```

Good thing is that I receive the custom action trace, and I display my custom message. 
What's happening though is that the client does not *stop* on the custom type, it just blows right through it. And in the screenshot above - you'll see that the *Speak* block will be executed by default path, without stopping.

**Comment by jonahsnider** [comment]
The current behavior of the client is to use the response handler set using `onResponse`, and falls back to the default response otherwise. From what I can see in your snippet because the handler isn't set using that method the client appears to be skipping through it.

Depending on what your `addTraceToBoard` function is doing, it shouldn't be too difficult to update it to look something like this:

```js
this.voiceflowClient.onResponse((trace) => {
  switch (trace.type) {
    case 'my custom trace 1':
      // First branch
      return 0;
    case 'my custom trace 2':
      // Second branch, etc.
      return 1;
    case 'my custom trace 3':
      // Fall back to default branch
      return undefined;
  }
})
```

Let me know if your issue is still occurring after making that change.

**Comment by fosteman** [comment]
Very good. Resolving the promise inside `onResponse` makes it usable.
```
const addTraceToBoard = (
  trace: any,
  context?: Context,
  index?: number
) =>
  new Promise((resolve) => {
switch (trace.type) {
    case 'my custom trace 1':
      // First branch
      resolve(0);
    case 'my custom trace 2':
      // Second branch, etc.
     resolve(1);
    case 'my custom trace 3':
      // Fall back to default branch
      resolve(undefined);
  }
}
this.voiceFlowClient.onResponse(addTraceToBoard);
```

**Comment by jonahsnider** [comment]
Great! Glad you were able to get your issue resolved.
